
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: "/"
  application:
    name: shipment-service
  profiles:
    active: local, swagger
  config:
    #    Imports configuration data from a config server when available
    #    import: "optional:configserver:"
    import: "configserver:http://localhost:6969"
    cloud:
      config:
        uri: ${CONFIG_SERVER_URL:http://localhost:6969}
        #      1
        request-connect-timeout: 5000
        #      2
        request-read-timeout: 5000
        #      3
        fail-fast: true
        retry:
          #        4
          max-attempts: 10
          #        5
          initial-interval: 1000
          #        6
          max-interval: 2000
          #        7
          multiplier: 1.1
          #1 Timeout on waiting to connect to the config server (ms)
          #2 Timeout on waiting to read configuration data from the config server (ms)
          #3 Makes a failure to connect to the config server fatal
          #4 Maximum number of attempts
          #5 Initial retry interval for backoff (ms)
          #6 Maximum retry interval for backoff (ms)
          #7 Multiplier to compute the next interval

server:
  port: 8004
queue:
  mall-shipments:
    queue:
    - mall-shipment-queue
    - order-status-update-queue
    exchange: mall-shipment-exchange
    routing-key:
    - mall-shipment-routing-key
    - shipment-status-update

